spring:
  application:
    name: Api-gateway

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Correct URL
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com:
      netflix: DEBUG
  org:
    springframework:
      cloud:
        netflix:
          eureka: DEBUG
